export enum RequestPackageTypes {
  BROADCAST_TRANSACTION = 24,
  REQUEST_TICK_INFO = 27,
  REQUEST_IDENTITY_BALANCE = 31,
  REQUEST_OWNED_ASSET = 38,
  REQUEST_POSSESSED_ASSET = 40,
}

export enum ResponsePackageTypes {
  RESPONSE_TICK_INFO = 28,
  RESPONSE_IDENTITY_BALANCE = 32,
  RESPONSE_OWNED_ASSET = 39,
  RESPONSE_POSSESSED_ASSET = 41,
}
